# -*- coding: utf-8 -*-
"""eco_tech

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V2uWXc2aIii93BwmZKIWNFZWPBjbTY_U
"""

!pip install -q transformers accelerate torch gradio gtts pydub
!apt-get -qq install -y ffmpeg

print("✅ All dependencies installed successfully!")

import gradio as gr
from transformers import pipeline
import torch
from gtts import gTTS
import os
from datetime import datetime
import tempfile
import json

# Check GPU availability
device = 0 if torch.cuda.is_available() else -1
print(f"🖥️ Using device: {'GPU' if device == 0 else 'CPU'}")

print("🔄 Loading IBM Granite 3.3 2B Instruct model...")
print("⏳ This may take a few minutes on first run...")

# Initialize the text generation pipeline with IBM Granite
text_generator = pipeline(
    "text-generation",
    model="ibm-granite/granite-3.3-2b-instruct",
    device=device,
    max_length=2048,
    temperature=0.7,
    top_p=0.9,
    do_sample=True
)

print("✅ Model loaded successfully!")

def rewrite_text_with_tone(original_text, tone):
    """
    Rewrites text using IBM Granite 3.3 2B Instruct with specified tone
    Uses prompt chaining for accurate tone adaptation
    """

    tone_prompts = {
        "Neutral": """Rewrite the following text in a clear, neutral, and professional tone.
Maintain all key information and facts while using objective language.
Keep the same meaning but make it suitable for formal narration.

Original text:
{text}

Rewritten text:""",

        "Suspenseful": """Rewrite the following text in a suspenseful and engaging tone.
Add dramatic elements, build tension, and create anticipation.
Use vivid descriptions and pacing to captivate the listener.
Maintain the core message while making it thrilling.

Original text:
{text}

Rewritten text:""",

        "Inspiring": """Rewrite the following text in an inspiring and motivational tone.
Use uplifting language, emphasize positive aspects, and encourage the listener.
Make it empowering and optimistic while preserving the original message.

Original text:
{text}

Rewritten text:"""
    }

    try:
        prompt = tone_prompts[tone].format(text=original_text)

        messages = [
            {"role": "user", "content": prompt}
        ]

        # Generate rewritten text
        response = text_generator(
            messages,
            max_new_tokens=1024,
            temperature=0.7,
            top_p=0.9,
            do_sample=True
        )

        # Extract generated text
        rewritten = response[0]['generated_text'][-1]['content'].strip()

        return rewritten

    except Exception as e:
        return f"Error during rewriting: {str(e)}"

def generate_audio(text, voice="en-US", slow=False):
    """
    Converts text to speech using gTTS (Google Text-to-Speech)
    Returns path to generated audio file
    """

    voice_mapping = {
        "Lisa (Female - US)": "en",
        "Michael (Male - UK)": "en-uk",
        "Allison (Female - AU)": "en-au"
    }

    try:
        # Create temporary file
        temp_file = tempfile.NamedTemporaryFile(delete=False, suffix=".mp3")

        # Generate TTS
        tts = gTTS(text=text, lang=voice_mapping.get(voice, "en"), slow=slow)
        tts.save(temp_file.name)

        return temp_file.name

    except Exception as e:
        print(f"Error generating audio: {str(e)}")
        return None

def process_text(input_text, file_upload, tone, voice):
    """
    Main processing function that handles:
    1. Text input (direct or file upload)
    2. Tone-adaptive rewriting
    3. Audio generation
    4. Side-by-side comparison
    """

    # Handle text input
    if file_upload is not None:
        try:
            original_text = file_upload.decode('utf-8')
        except:
            return (
                "❌ Error reading file. Please ensure it's a valid .txt file.",
                "",
                "",
                None
            )
    elif input_text and input_text.strip():
        original_text = input_text.strip()
    else:
        return (
            "⚠️ Please provide text input or upload a .txt file.",
            "",
            "",
            None
        )

    # Validate text length
    if len(original_text) < 10:
        return (
            "⚠️ Text is too short. Please provide at least 10 characters.",
            "",
            "",
            None
        )

    # Step 1: Rewrite text with selected tone
    status_msg = f"🔄 Rewriting text with {tone} tone..."
    print(status_msg)

    rewritten_text = rewrite_text_with_tone(original_text, tone)

    # Step 2: Generate audio from rewritten text
    status_msg = f"🎵 Generating audio with {voice} voice..."
    print(status_msg)

    audio_path = generate_audio(rewritten_text, voice)

    if audio_path is None:
        return (
            original_text,
            rewritten_text,
            "❌ Error generating audio",
            None
        )

    # Step 3: Prepare comparison view
    comparison = f"""
📄 ORIGINAL TEXT ({len(original_text)} characters):
{'-' * 80}
{original_text}

{'=' * 80}

✨ REWRITTEN TEXT - {tone.upper()} TONE ({len(rewritten_text)} characters):
{'-' * 80}
{rewritten_text}
"""

    success_msg = f"✅ Successfully generated {tone} audiobook with {voice} voice!"

    return (
        original_text,
        rewritten_text,
        comparison,
        audio_path
    )

def create_interface():
    """
    Creates the professional Gradio interface for EchoVerse
    """

    # Custom CSS for professional styling
    custom_css = """
    .container {
        max-width: 1200px;
        margin: auto;
    }
    .header {
        text-align: center;
        padding: 20px;
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        color: white;
        border-radius: 10px;
        margin-bottom: 20px;
    }
    .feature-box {
        background: #f8f9fa;
        padding: 15px;
        border-radius: 8px;
        border-left: 4px solid #667eea;
        margin: 10px 0;
    }
    """

    with gr.Blocks(css=custom_css, title="EchoVerse - AI Audiobook Creator") as app:

        # Header
        gr.HTML("""
        <div class="header">
            <h1>🎙️ EchoVerse</h1>
            <h3>AI-Powered Audiobook Creation System</h3>
            <p>Transform your text into expressive, downloadable audio content</p>
            <p><em>Powered by IBM Granite 3.3 2B Instruct</em></p>
        </div>
        """)

        # Features Overview
        with gr.Row():
            gr.HTML("""
            <div class="feature-box">
                <h4>✨ Key Features:</h4>
                <ul>
                    <li>🎭 <strong>Tone-Adaptive Rewriting</strong> - Neutral, Suspenseful, or Inspiring</li>
                    <li>🗣️ <strong>Natural Voice Narration</strong> - Multiple voice options</li>
                    <li>💾 <strong>Downloadable Audio</strong> - MP3 format for offline use</li>
                    <li>📊 <strong>Side-by-Side Comparison</strong> - Original vs. Rewritten text</li>
                </ul>
            </div>
            """)

        # Main Interface
        with gr.Row():
            # Left Column - Input
            with gr.Column(scale=1):
                gr.Markdown("### 📝 Input Text")

                input_text = gr.Textbox(
                    label="Paste Your Text Here",
                    placeholder="Enter the text you want to convert to audiobook...",
                    lines=10,
                    max_lines=15
                )

                file_upload = gr.File(
                    label="Or Upload .txt File",
                    file_types=[".txt"],
                    type="binary"
                )

                gr.Markdown("### ⚙️ Settings")

                tone_choice = gr.Radio(
                    choices=["Neutral", "Suspenseful", "Inspiring"],
                    value="Neutral",
                    label="Select Tone",
                    info="Choose how the text should be rewritten"
                )

                voice_choice = gr.Radio(
                    choices=[
                        "Lisa (Female - US)",
                        "Michael (Male - UK)",
                        "Allison (Female - AU)"
                    ],
                    value="Lisa (Female - US)",
                    label="Select Voice",
                    info="Choose the narrator's voice"
                )

                generate_btn = gr.Button(
                    "🎬 Generate Audiobook",
                    variant="primary",
                    size="lg"
                )

            # Right Column - Output
            with gr.Column(scale=1):
                gr.Markdown("### 🎧 Audio Output")

                audio_output = gr.Audio(
                    label="Generated Audiobook",
                    type="filepath",
                    interactive=False
                )

                gr.Markdown("### 📊 Text Comparison")

                with gr.Tabs():
                    with gr.Tab("Original Text"):
                        original_display = gr.Textbox(
                            label="Original Text",
                            lines=8,
                            max_lines=12,
                            interactive=False
                        )

                    with gr.Tab("Rewritten Text"):
                        rewritten_display = gr.Textbox(
                            label="Rewritten Text",
                            lines=8,
                            max_lines=12,
                            interactive=False
                        )

                    with gr.Tab("Side-by-Side"):
                        comparison_display = gr.Textbox(
                            label="Comparison View",
                            lines=15,
                            max_lines=20,
                            interactive=False
                        )

        # Examples Section
        gr.Markdown("### 💡 Example Texts to Try")

        gr.Examples(
            examples=[
                [
                    "Artificial intelligence is transforming the way we work and live. From healthcare to transportation, AI systems are becoming increasingly capable of performing complex tasks that once required human intelligence.",
                    "Inspiring"
                ],
                [
                    "The old mansion stood at the end of the dark street. Nobody had entered it for decades. Tonight, something was different. A light flickered in the top window.",
                    "Suspenseful"
                ],
                [
                    "Climate change represents one of the most significant challenges of our time. Rising temperatures, extreme weather events, and ecosystem disruption require immediate action.",
                    "Neutral"
                ]
            ],
            inputs=[input_text, tone_choice],
            label="Click any example to load it"
        )

        # Connect the generation button
        generate_btn.click(
            fn=process_text,
            inputs=[input_text, file_upload, tone_choice, voice_choice],
            outputs=[
                original_display,
                rewritten_display,
                comparison_display,
                audio_output
            ]
        )

        # Footer
        gr.HTML("""
        <div style="text-align: center; padding: 20px; margin-top: 30px; border-top: 1px solid #ddd;">
            <p><strong>EchoVerse</strong> - Empowering accessibility through AI</p>
            <p><em>Built with IBM Granite 3.3 2B Instruct & Gradio</em></p>
        </div>
        """)

    return app

# Create and launch the interface
print("🚀 Launching EchoVerse...")
app = create_interface()

# Launch with public sharing enabled for Colab
app.launch(
    share=True,
    debug=True,
    server_name="0.0.0.0",
    server_port=7860
)

print("✅ EchoVerse is now running!")
print("🌐 Access the application using the public URL above")